### ISSUE TITLE
沒甚麼故障一切都很好只是對食物相關有疑問

### ISSUE THREAD

**Issue by zhigk** [emicoto/DOLMods#19]
能不額外做一個不含飢渴質的版本，我愣是找不到喝水的地方狂喊快渴死了

**Comment by Mioter** [comment]
> 能不額外做一個不含飢渴質的版本，我愣是找不到喝水的地方狂喊快渴死了

i添加的购物超市饮料分类里有矿泉水，还有其他饮料
