### ISSUE TITLE
在旁加载mod拥有Simple Frameworks时，跳转场景可能会报错

### ISSUE THREAD

**Issue by mihonskka** [emicoto/DOLMods#23]
![image](https://github.com/user-attachments/assets/60d177ce-5f3e-4ee9-93a4-a638f5dbe6c0)
此时创建基础存档并进入游戏，从孤儿院离开。
![image](https://github.com/user-attachments/assets/9fb2079a-f084-42b8-96b2-fcbd9b6e2682)
离开后点击next，出现报错。
![image](https://github.com/user-attachments/assets/6fab2b6e-0806-4641-8d44-9ac31aa92c69)
报错完整内容如下：
![image](https://github.com/user-attachments/assets/2051cb2c-b35a-4afd-9560-284929180e82)

但游戏依然可以继续。游玩不受影响。

在加载了ModI18N-0.5.0.6-chs-2.1.0a.mod（中文汉化）和GameOriginalImagePack-0.5.0.6.mod后再加载Simple Frameworks，也会出现这一问题，且报错信息一致。

希望隐藏此报错。
游戏版本：5.0.6

**Comment by emicoto** [comment]
已修复
